name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Distribute apk to the Firebase
      run: |
        ls -la app/build/outputs/apk/debug
        sudo apt-get install -y curl
        curl -sL https://firebase.tools | bash
        firebase appdistribution:distribute --app com.my.shashlik --groups testers app/build/outputs/apk/debug/app-debug.apk
